config/routes.rb
Rails.application.routes.draw do
  root "staticpages#index"
  namespace :api, defaults: { format: :json } do
    resources :users, only: [:index, :show, :create]
    resource :session, only: [:new, :create, :destroy]
    resources :photos, except: [:new, :edit]
    resources :subscriptions, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :update, :destroy]
  end
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Geofotr</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li id='add-dropdown' class='dropdown'>
            <button
              class='dropdown-toggle navbar-btn btn btn-primary'
              data-toggle='dropdown'><span>Geofotr a photo!</span>
            </button>
          </li>
          <li><%= link_to "Map", "#map" %></li>
          <li><%= link_to "Feed", "" %></li>
          <li><%= link_to "Your photos", "#users/" + current_user.id.to_s %></li>
          <li><%= link_to "Users", "#users" %></li>
          <li><%= link_to "Sign Out", session_url, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_url %></li>
          <li><%= link_to "Sign In", new_session_url %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_signout.html.erb
<form action="<%= session_url %>"method="POST">
  <input type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">

  <input type="hidden"
            name="_method"
            value="DELETE">

  <input type="submit" value="Sign Out">
</form>